export interface TutorialStep {
  id: string
  path: string
  section: string
  title: string
  body: string
}

/** Guided tour — every app section and major capability. */
export const tutorialSteps: TutorialStep[] = [
  {
    id: 'welcome',
    path: '/app',
    section: 'Alivia',
    title: 'Bienvenido a Alivia',
    body: 'Esta guía recorre cada módulo y capacidad de la plataforma. Usa Siguiente para avanzar o Ocultar guía abajo cuando quieras explorar solo.',
  },
  {
    id: 'nav',
    path: '/app',
    section: 'Navegación',
    title: 'Menú lateral',
    body: 'Cinco familias: Inicio, Inteligencia diaria, Clínico, Biblioteca y Estudio. Al entrar a cada una verás sub-secciones en la barra superior.',
  },
  {
    id: 'dashboard',
    path: '/app',
    section: 'Inicio',
    title: 'Resumen del día',
    body: 'Accesos rápidos a briefing, rondas pendientes y biblioteca. El bloque central muestra planes de manejo con ítems por cerrar.',
  },
  {
    id: 'briefing',
    path: '/app/briefing',
    section: 'Inteligencia diaria',
    title: 'Resumen de hoy',
    body: 'Feed matutino con guías actualizadas, congresos y artículos nuevos en tu especialidad. Filtra por especialidades y marca cards como no relevantes.',
  },
  {
    id: 'briefing-save',
    path: '/app/briefing',
    section: 'Inteligencia diaria',
    title: 'Guardar en biblioteca',
    body: 'Desde cualquier card del briefing puedes guardar el artículo en tu biblioteca para resumirlo, hacer quiz o generar podcast después.',
  },
  {
    id: 'trending',
    path: '/app/briefing/citados',
    section: 'Alta citación',
    title: 'Artículos más citados',
    body: 'Descubre papers de alto impacto en tu área. Úsalos para preparar journal club o reforzar un argumento en ronda.',
  },
  {
    id: 'ronda-intro',
    path: '/app/ronda',
    section: 'Clínico · Ronda',
    title: 'La Ronda — flujo en 4 pasos',
    body: 'Graba, sube audio o pega texto del caso. Alivia extrae términos, busca PubMed y genera planes citados con las fuentes que elijas.',
  },
  {
    id: 'ronda-input',
    path: '/app/ronda',
    section: 'Paso 1 · Entrada',
    title: 'Captura del encuentro',
    body: 'Elige grabar en la ronda, subir un archivo o escribir el texto. El progreso se guarda automáticamente en la barra superior.',
  },
  {
    id: 'ronda-mesh',
    path: '/app/ronda',
    section: 'Paso 2 · Términos',
    title: 'Términos MeSH y clínicos',
    body: 'Revisa y edita los términos que alimentan la búsqueda PubMed. Puedes agregar o quitar etiquetas antes de buscar.',
  },
  {
    id: 'ronda-pubmed',
    path: '/app/ronda',
    section: 'Paso 3 · PubMed',
    title: 'Selección de papers',
    body: 'Marca los artículos que respaldarán tu plan. Los seleccionados van a la biblioteca al generar los planes.',
  },
  {
    id: 'ronda-plans',
    path: '/app/ronda',
    section: 'Paso 4 · Planes',
    title: 'Plan de manejo y de estudio',
    body: 'Cada afirmación del plan enlaza a un PMID real. El plan de estudio incluye lecturas, borrador de respuesta y quiz del especialista.',
  },
  {
    id: 'toolkit-intro',
    path: '/app/ronda',
    section: 'Toolkit de evidencia',
    title: 'Generar desde tus papers',
    body: 'El toolkit aparece en Ronda, Consulta y Biblioteca. Con los papers seleccionados puedes crear presentación, quiz, podcast y chat.',
  },
  {
    id: 'toolkit-presentation',
    path: '/app/ronda',
    section: 'Presentación',
    title: 'Presentación citada',
    body: 'Genera diapositivas HTML con citas PMID. Se guarda en Biblioteca → Presentaciones y puedes descargarla al instante.',
  },
  {
    id: 'toolkit-quiz',
    path: '/app/ronda',
    section: 'Quiz',
    title: 'Quiz de 5 preguntas',
    body: 'Preguntas basadas en tus fuentes, con feedback por ítem y global. El historial de intentos queda en Biblioteca → Cuestionarios.',
  },
  {
    id: 'toolkit-podcast',
    path: '/app/ronda',
    section: 'Podcast',
    title: 'Podcast multilingüe',
    body: 'Elige español, inglés o portugués y versión lite o completa. Descarga audio WAV y guion TXT; se guarda en Biblioteca → Podcasts.',
  },
  {
    id: 'toolkit-chat',
    path: '/app/ronda',
    section: 'Chat',
    title: 'Chat con contexto',
    body: 'Pregunta sobre el paciente y los papers seleccionados. Las respuestas citan PMIDs — sin inventar referencias.',
  },
  {
    id: 'consulta-intro',
    path: '/app/consulta',
    section: 'Clínico · Consulta',
    title: 'Nueva consulta clínica',
    body: 'Plantea una pregunta PICO, busca en PubMed y obtén una respuesta citada para el caso.',
  },
  {
    id: 'consulta-pico',
    path: '/app/consulta',
    section: 'Consulta · PICO',
    title: 'Caso y PICO',
    body: 'Define paciente, pregunta clínica e intervención/comparador/desenlace. Pulsa Buscar en PubMed para ver resultados clasificados.',
  },
  {
    id: 'consulta-results',
    path: '/app/consulta',
    section: 'Consulta · Fuentes',
    title: 'Elegir fuentes',
    body: 'Selecciona papers para la respuesta y para el toolkit. También puedes generar presentación, quiz o podcast desde aquí.',
  },
  {
    id: 'consulta-answer',
    path: '/app/consulta',
    section: 'Consulta · Respuesta',
    title: 'Respuesta citada',
    body: 'Al generar la respuesta se crea un plan de manejo en Estudio y quedan las fuentes enlazadas a PubMed.',
  },
  {
    id: 'library-papers',
    path: '/app/biblioteca',
    section: 'Biblioteca · Papers',
    title: 'Tus papers guardados',
    body: 'Artículos de rondas, consultas o briefing. Haz clic en uno para ver el resumen estructurado y el toolkit.',
  },
  {
    id: 'library-upload',
    path: '/app/biblioteca',
    section: 'Biblioteca · Subir',
    title: 'Importar por PMID',
    body: 'Sube un paper manualmente con su PMID. Se añade a la lista y puedes usarlo igual que el resto.',
  },
  {
    id: 'library-search',
    path: '/app/biblioteca',
    section: 'Biblioteca · Buscar',
    title: 'Buscar por título o DOI',
    body: 'Filtra tu biblioteca y navega con paginación. El contador del tab muestra el total de papers guardados.',
  },
  {
    id: 'library-summary',
    path: '/app/biblioteca',
    section: 'Biblioteca · Resumen',
    title: 'Resumen estructurado',
    body: 'Pregunta, métodos, hallazgos, conclusión y limitaciones. Marca leído/pendiente y vuelve a la búsqueda original.',
  },
  {
    id: 'library-presentaciones',
    path: '/app/biblioteca/presentaciones',
    section: 'Biblioteca · Presentaciones',
    title: 'Presentaciones guardadas',
    body: 'Cada presentación enlaza a la búsqueda que la originó. Descarga el HTML de diapositivas cuando la necesites.',
  },
  {
    id: 'library-cuestionarios',
    path: '/app/biblioteca/cuestionarios',
    section: 'Biblioteca · Cuestionarios',
    title: 'Historial de quizzes',
    body: 'Un quiz por contexto de búsqueda. Expande para ver intentos por fecha y puntuación, con paginación.',
  },
  {
    id: 'library-podcasts',
    path: '/app/biblioteca/podcasts',
    section: 'Biblioteca · Podcasts',
    title: 'Podcasts guardados',
    body: 'Audios generados desde tus búsquedas. Descarga WAV y guion; cada ítem recuerda idioma y versión.',
  },
  {
    id: 'study-plans',
    path: '/app/tareas',
    section: 'Estudio',
    title: 'Planes de manejo',
    body: 'Afirmaciones citadas por paciente o caso. Cada plan enlaza a la ronda o consulta que lo generó.',
  },
  {
    id: 'study-items',
    path: '/app/tareas',
    section: 'Estudio · Ítems',
    title: 'Priorizar y completar',
    body: 'Toca la etiqueta de prioridad (alta/media/baja) para rotarla. Marca ítems al cerrar el plan clínico.',
  },
  {
    id: 'notifications',
    path: '/app',
    section: 'Notificaciones',
    title: 'Campana de avisos',
    body: 'Te avisa cuando una presentación, quiz o podcast termina de generarse, con enlace directo a Biblioteca.',
  },
  {
    id: 'perfil',
    path: '/app/perfil',
    section: 'Perfil',
    title: 'Perfil y plan',
    body: 'Revisa tu especialidad, año de formación y estado de suscripción mock.',
  },
  {
    id: 'ayuda',
    path: '/app/ayuda',
    section: 'Ayuda',
    title: 'Soporte',
    body: 'Preguntas frecuentes y contacto. Puedes reactivar esta guía cuando quieras con el botón inferior.',
  },
  {
    id: 'done',
    path: '/app',
    section: 'Listo',
    title: '¡Tour completado!',
    body: 'Ya conoces todas las secciones. Oculta la guía abajo o vuelve a cualquier paso con Anterior. ¡Buena ronda!',
  },
]
